# src/main/resources/application.yml
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oxxo?useSSL=false&serverTimezone=America/Lima
    username: root
    password: andres123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # dialect opcional; Hibernate 6 autodetecta, pero puedes forzar:
        # dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never          # no ejecutar data.sql / schema.sql

  flyway:
    enabled: false         # evita "Unsupported Database: MySQL 9.0"

logging:
  level:
    org.springframework.security: info
    org.hibernate.SQL: warn
